# Generated by Django 4.1.2 on 2022-10-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfg', '0003_mymodel_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='GeeksforGeeks',
        ),
    ]
